workspaces:
- name: easy-squirrel
  organization: Fricory
- name: easy-squirrel-2
  organization: Fricory
  dirs:
    - aws/workspaces
- name: easy-squirrel-3
  organization: Fricory
  dirs:
    - workspaces
